apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-hec-appdata
  namespace: splunk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
